server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ziyiqingspace?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 264047
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
    main:
      allow-circular-references: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  http:
    converters:
      preferred-json-mapper: jackson # 设置使用 Jackson 作为首选的 JSON 转换器
    mvc:
      message-converters:
        pre-established-media-types: # 在这里配置支持的媒体类型
          application/json: true
        jackson:
          pretty-print: true # Jackson 转换器的配置选项
ziyiqingSpace:
  path: C:\Users\yaoyuhang\Desktop\ziyiqingSpace\ZiyiqingSpace-java\src\main\resources\static\article\
  photographypath: C:\Users\yaoyuhang\Desktop\ziyiqingSpace\ZiyiqingSpace-java\src\main\resources\static\photography\

